// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { BlinnMotion, type BlinnMotionHandle } from "@blinn-motion/vue";
import { fixtures, type FixtureId } from "../../_shared/fixtures";

const fixtureMeta: { id: FixtureId; label: string; note: string }[] = [
  { id: "card", label: "Card intro", note: "1.6s product card spring" },
  { id: "showcase", label: "Showcase", note: "gradients · trim · multi-layer" },
];

const docId = ref<FixtureId>("showcase");
const doc = computed(() => fixtures[docId.value]);
const fixtureNote = computed(() => fixtureMeta.find((f) => f.id === docId.value)?.note ?? "");
const mode = ref<"clock" | "progress">("clock");
const progress = ref(0);
const rate = ref(1);
const playing = ref(true);
const time = ref(0);
const fraction = ref(0);
const scrub = ref(0);
const rates = [0.5, 1, 1.5, 2];

const domRef = ref<BlinnMotionHandle | null>(null);
const canvasRef = ref<BlinnMotionHandle | null>(null);
const progressProp = computed(() => (mode.value === "progress" ? progress.value : undefined));
const duration = computed(() => doc.value.duration ?? 1);

const CASES = [
  { k: "Doc switch", v: "card + showcase fixtures" },
  { k: "Dual stages", v: "DOM vs Canvas, same MotionDoc" },
  { k: "Transport", v: "play · pause · toggle · restart" },
  { k: "Scrub + rate", v: "seekFraction · setRate" },
  { k: "Progress mode", v: "controlled 0…1 prop" },
  { k: "onFrame meter", v: "live time + fraction" },
];

function both(fn: (h: BlinnMotionHandle | null) => void) {
  fn(domRef.value);
  fn(canvasRef.value);
}

function onFrame(t: number, f: number) {
  time.value = t;
  fraction.value = f;
  if (mode.value === "clock") scrub.value = f;
}

function applyMode(m: "clock" | "progress") {
  mode.value = m;
  if (m === "progress") {
    both((h) => h?.pause());
    playing.value = false;
    progress.value = scrub.value;
  } else {
    both((h) => {
      h?.seekFraction(scrub.value);
      h?.play();
    });
    playing.value = true;
  }
}

function toggle() {
  both((h) => h?.toggle());
  playing.value = !playing.value;
}

function restart() {
  both((h) => {
    h?.seek(0);
    if (mode.value === "clock") h?.play();
  });
  playing.value = mode.value === "clock";
  scrub.value = 0;
  progress.value = 0;
  time.value = 0;
  fraction.value = 0;
}

function onScrub(v: number) {
  scrub.value = v;
  if (mode.value === "progress") progress.value = v;
  else {
    both((h) => {
      h?.pause();
      h?.seekFraction(v);
    });
    playing.value = false;
  }
}

function setRate(r: number) {
  rate.value = r;
  both((h) => h?.setRate(r));
}

watch(docId, () => {
  playing.value = mode.value === "clock";
  scrub.value = 0;
  progress.value = 0;
  time.value = 0;
  fraction.value = 0;
});
</script>

<template>
  <div class="lab">
    <header class="lab-top">
      <a class="lab-brand" href="https://blinnmotion.com" target="_blank" rel="noreferrer">
        <span class="lab-mark">
          <svg viewBox="0 0 64 64" width="22" height="22" aria-hidden>
            <rect x="6" y="6" width="52" height="52" rx="15" fill="#11141A" />
            <g fill="none" stroke="#fff" stroke-width="6.2" stroke-linecap="round" stroke-linejoin="round">
              <path d="M24 18 V46" />
              <path d="M24 18 H32.5 C38.6 18 38.6 32 32.5 32 H24" />
              <path d="M24 32 H34.5 C41.2 32 41.2 46 34.5 46 H24" />
            </g>
            <rect x="43.6" y="43.6" width="7.6" height="7.6" rx="1.5" transform="rotate(45 47.4 47.4)" fill="#2F6BFF" />
          </svg>
        </span>
        <span>
          <div class="lab-brand-name">Blinn Motion</div>
          <div class="lab-brand-sub">Example lab</div>
        </span>
      </a>
      <div class="lab-top-grow" />
      <nav class="lab-top-links">
        <a class="lab-link" href="https://docs.blinnmotion.com/adapters/vue" target="_blank" rel="noreferrer">Vue docs ↗</a>
        <a class="lab-link" href="https://docs.blinnmotion.com" target="_blank" rel="noreferrer">All docs ↗</a>
      </nav>
    </header>

    <div class="lab-header">
      <div class="stack-pill"><span class="dot" /> Vue 3 · @blinn-motion/vue</div>
      <h1 class="lab-title">Dual-backend motion lab <em>in Vue</em></h1>
      <p class="lab-lede">
        Same advanced flow as React: dual <code>dom</code> / <code>canvas</code> stages, transport,
        scrub, rate, and progress-driven mode via <code>&lt;BlinnMotion&gt;</code>.
      </p>
    </div>

    <div class="lab-grid">
      <section class="card">
        <div class="card-head">
          <h2>Stage bay</h2>
          <span class="card-meta">{{ fixtureNote }}</span>
        </div>
        <div class="card-body">
          <div class="stages">
            <div class="stage">
              <div class="stage-bar">
                <span class="tag dom">dom</span>
                <span class="hint">CSS · SVG · full fidelity</span>
              </div>
              <div class="stage-host">
                <BlinnMotion
                  ref="domRef"
                  :doc="doc"
                  renderer="dom"
                  :loop="true"
                  :autoplay="mode === 'clock'"
                  :rate="rate"
                  :progress="progressProp"
                  :on-frame="onFrame"
                />
              </div>
            </div>
            <div class="stage">
              <div class="stage-bar">
                <span class="tag canvas">canvas</span>
                <span class="hint">immediate-mode 2D</span>
              </div>
              <div class="stage-host">
                <BlinnMotion
                  ref="canvasRef"
                  :doc="doc"
                  renderer="canvas"
                  :loop="true"
                  :autoplay="mode === 'clock'"
                  :rate="rate"
                  :progress="progressProp"
                />
              </div>
            </div>
          </div>
        </div>
      </section>

      <aside class="card">
        <div class="card-head">
          <h2>Director console</h2>
          <span class="card-meta">live</span>
        </div>
        <div class="card-body">
          <div class="console-section">
            <span class="console-label">MotionDoc</span>
            <div class="seg">
              <button
                v-for="f in fixtureMeta"
                :key="f.id"
                type="button"
                :class="{ on: docId === f.id }"
                @click="docId = f.id"
              >
                {{ f.label }}
              </button>
            </div>
          </div>

          <div class="console-section">
            <span class="console-label">Transport</span>
            <div class="transport">
              <button type="button" class="btn btn-primary" @click="toggle">
                {{ playing ? "❚❚ Pause" : "▶ Play" }}
              </button>
              <button type="button" class="btn btn-ghost" @click="restart">↺ Restart</button>
            </div>
          </div>

          <div class="console-section">
            <span class="console-label">Timeline</span>
            <div class="meter-block">
              <div class="meter-row">
                <span class="meter-time">
                  {{ time.toFixed(2) }}s
                  <span style="color: var(--ink-3); font-weight: 500; font-size: 13px">
                    / {{ duration.toFixed(2) }}s
                  </span>
                </span>
                <span class="meter-frac">{{ Math.round(fraction * 100) }}% · f={{ fraction.toFixed(3) }}</span>
              </div>
              <input
                class="scrub"
                type="range"
                min="0"
                max="1"
                step="0.001"
                :value="mode === 'progress' ? progress : scrub"
                @input="onScrub(Number(($event.target as HTMLInputElement).value))"
              />
            </div>
          </div>

          <div class="console-section">
            <span class="console-label">Rate</span>
            <div class="seg">
              <button
                v-for="r in rates"
                :key="r"
                type="button"
                :class="{ on: rate === r }"
                @click="setRate(r)"
              >
                {{ r }}×
              </button>
            </div>
          </div>

          <div class="console-section">
            <span class="console-label">Drive mode</span>
            <div class="seg">
              <button type="button" :class="{ on: mode === 'clock' }" @click="applyMode('clock')">Clock</button>
              <button type="button" :class="{ on: mode === 'progress' }" @click="applyMode('progress')">
                Progress
              </button>
            </div>
            <p class="mode-note">
              <template v-if="mode === 'clock'">
                <strong>Clock-driven</strong> — shared ticker. Scrub pauses and seeks.
              </template>
              <template v-else>
                <strong>Progress-driven</strong> — controlled <code>progress</code> prop (0…1).
              </template>
            </p>
          </div>
        </div>
      </aside>
    </div>

    <section class="card cases">
      <div class="card-head">
        <h2>Covered cases</h2>
        <span class="card-meta">shared example flow</span>
      </div>
      <div class="card-body">
        <div class="case-grid">
          <div v-for="c in CASES" :key="c.k" class="case">
            <div class="k"><span class="check">✓</span>{{ c.k }}</div>
            <div class="v">{{ c.v }}</div>
          </div>
        </div>
      </div>
    </section>

    <footer class="lab-foot">
      <span>Package <code class="mono">@blinn-motion/vue</code></span>
      <span class="sep">·</span>
      <a href="https://docs.blinnmotion.com/adapters/vue" target="_blank" rel="noreferrer">Adapter docs</a>
      <span class="sep">·</span>
      <a href="https://blinnmotion.com" target="_blank" rel="noreferrer">blinnmotion.com</a>
    </footer>
  </div>
</template>

// examples/react/src/App.tsx
import { useCallback, useMemo, useRef, useState } from "react";
import { BlinnMotion, type BlinnMotionHandle } from "@blinn-motion/react";
import type { MotionDoc } from "@blinn-motion/core";
import card from "../../../fixtures/card.motion.json";
import showcase from "../../../fixtures/showcase.motion.json";
import "../../_shared/lab.css";

type FixtureId = "card" | "showcase";
type Mode = "clock" | "progress";

const fixtures: Record<FixtureId, MotionDoc> = {
  card: card as MotionDoc,
  showcase: showcase as MotionDoc,
};

const fixtureMeta: { id: FixtureId; label: string; note: string }[] = [
  { id: "card", label: "Card intro", note: "1.6s product card spring" },
  { id: "showcase", label: "Showcase", note: "gradients · trim · multi-layer" },
];

const rates = [0.5, 1, 1.5, 2];

const CASES = [
  { k: "Doc switch", v: "card + showcase fixtures" },
  { k: "Dual stages", v: "DOM vs Canvas, same MotionDoc" },
  { k: "Transport", v: "play · pause · toggle · restart" },
  { k: "Scrub + rate", v: "seekFraction · setRate" },
  { k: "Progress mode", v: "controlled 0…1 prop" },
  { k: "onFrame meter", v: "live time + fraction" },
];

function BrandMark() {
  return (
    <svg viewBox="0 0 64 64" width="22" height="22" aria-hidden>
      <rect x="6" y="6" width="52" height="52" rx="15" fill="#11141A" />
      <g fill="none" stroke="#fff" strokeWidth="6.2" strokeLinecap="round" strokeLinejoin="round">
        <path d="M24 18 V46" />
        <path d="M24 18 H32.5 C38.6 18 38.6 32 32.5 32 H24" />
        <path d="M24 32 H34.5 C41.2 32 41.2 46 34.5 46 H24" />
      </g>
      <rect x="43.6" y="43.6" width="7.6" height="7.6" rx="1.5" transform="rotate(45 47.4 47.4)" fill="#2F6BFF" />
    </svg>
  );
}

export function App() {
  const domRef = useRef<BlinnMotionHandle>(null);
  const canvasRef = useRef<BlinnMotionHandle>(null);

  const [docId, setDocId] = useState<FixtureId>("showcase");
  const [mode, setMode] = useState<Mode>("clock");
  const [progress, setProgress] = useState(0);
  const [rate, setRate] = useState(1);
  const [playing, setPlaying] = useState(true);
  const [time, setTime] = useState(0);
  const [fraction, setFraction] = useState(0);
  const [scrub, setScrub] = useState(0);

  const doc = fixtures[docId];
  const duration = doc.duration ?? 1;
  const progressProp = mode === "progress" ? progress : undefined;

  const both = useCallback((fn: (h: BlinnMotionHandle | null) => void) => {
    fn(domRef.current);
    fn(canvasRef.current);
  }, []);

  const onFrame = useCallback(
    (t: number, f: number) => {
      setTime(t);
      setFraction(f);
      if (mode === "clock") setScrub(f);
    },
    [mode],
  );

  const applyMode = (m: Mode) => {
    setMode(m);
    if (m === "progress") {
      both((h) => h?.pause());
      setPlaying(false);
      setProgress(scrub);
    } else {
      both((h) => {
        h?.seekFraction(scrub);
        h?.play();
      });
      setPlaying(true);
    }
  };

  const fixtureNote = useMemo(
    () => fixtureMeta.find((f) => f.id === docId)?.note ?? "",
    [docId],
  );

  return (
    <div className="lab">
      <header className="lab-top">
        <a className="lab-brand" href="https://blinnmotion.com" target="_blank" rel="noreferrer">
          <span className="lab-mark">
            <BrandMark />
          </span>
          <span>
            <div className="lab-brand-name">Blinn Motion</div>
            <div className="lab-brand-sub">Example lab</div>
          </span>
        </a>
        <div className="lab-top-grow" />
        <nav className="lab-top-links">
          <a className="lab-link" href="https://docs.blinnmotion.com/adapters/react" target="_blank" rel="noreferrer">
            React docs ↗
          </a>
          <a className="lab-link" href="https://docs.blinnmotion.com" target="_blank" rel="noreferrer">
            All docs ↗
          </a>
          <a className="lab-link" href="https://github.com/ismailyagci/blinn-motion/tree/main/examples" target="_blank" rel="noreferrer">
            Examples ↗
          </a>
        </nav>
      </header>

      <div className="lab-header">
        <div className="stack-pill">
          <span className="dot" />
          React · @blinn-motion/react
        </div>
        <h1 className="lab-title">
          Dual-backend motion lab <em>in React</em>
        </h1>
        <p className="lab-lede">
          One <code>MotionDoc</code>, two painters — <code>renderer=&quot;dom&quot;</code> and{" "}
          <code>renderer=&quot;canvas&quot;</code> — sharing core timing. Switch fixtures, scrub the
          timeline, flip into progress-driven mode for scroll/gesture patterns.
        </p>
      </div>

      <div className="lab-grid">
        {/* Theater */}
        <section className="card">
          <div className="card-head">
            <h2>Stage bay</h2>
            <span className="card-meta">{fixtureNote}</span>
          </div>
          <div className="card-body">
            <div className="stages">
              <div className="stage">
                <div className="stage-bar">
                  <span className="tag dom">dom</span>
                  <span className="hint">CSS · SVG · full fidelity</span>
                </div>
                <div className="stage-host">
                  <BlinnMotion
                    ref={domRef}
                    doc={doc}
                    renderer="dom"
                    loop
                    autoplay={mode === "clock"}
                    rate={rate}
                    progress={progressProp}
                    onFrame={onFrame}
                  />
                </div>
              </div>
              <div className="stage">
                <div className="stage-bar">
                  <span className="tag canvas">canvas</span>
                  <span className="hint">immediate-mode 2D</span>
                </div>
                <div className="stage-host">
                  <BlinnMotion
                    ref={canvasRef}
                    doc={doc}
                    renderer="canvas"
                    loop
                    autoplay={mode === "clock"}
                    rate={rate}
                    progress={progressProp}
                  />
                </div>
              </div>
            </div>
          </div>
        </section>

        {/* Console */}
        <aside className="card">
          <div className="card-head">
            <h2>Director console</h2>
            <span className="card-meta">live</span>
          </div>
          <div className="card-body">
            <div className="console-section">
              <span className="console-label">MotionDoc</span>
              <div className="seg">
                {fixtureMeta.map((f) => (
                  <button
                    key={f.id}
                    type="button"
                    className={docId === f.id ? "on" : ""}
                    onClick={() => {
                      setDocId(f.id);
                      setPlaying(mode === "clock");
                      setScrub(0);
                      setProgress(0);
                      setTime(0);
                      setFraction(0);
                    }}
                  >
                    {f.label}
                  </button>
                ))}
              </div>
            </div>

            <div className="console-section">
              <span className="console-label">Transport</span>
              <div className="transport">
                <button
                  type="button"
                  className="btn btn-primary"
                  onClick={() => {
                    both((h) => h?.toggle());
                    setPlaying((p) => !p);
                  }}
                >
                  {playing ? "❚❚ Pause" : "▶ Play"}
                </button>
                <button
                  type="button"
                  className="btn btn-ghost"
                  onClick={() => {
                    both((h) => {
                      h?.seek(0);
                      if (mode === "clock") h?.play();
                    });
                    setPlaying(mode === "clock");
                    setScrub(0);
                    setProgress(0);
                    setTime(0);
                    setFraction(0);
                  }}
                >
                  ↺ Restart
                </button>
              </div>
            </div>

            <div className="console-section">
              <span className="console-label">Timeline</span>
              <div className="meter-block">
                <div className="meter-row">
                  <span className="meter-time">
                    {time.toFixed(2)}s
                    <span style={{ color: "var(--ink-3)", fontWeight: 500, fontSize: 13 }}>
                      {" "}
                      / {duration.toFixed(2)}s
                    </span>
                  </span>
                  <span className="meter-frac">{Math.round(fraction * 100)}% · f={fraction.toFixed(3)}</span>
                </div>
                <input
                  className="scrub"
                  type="range"
                  min={0}
                  max={1}
                  step={0.001}
                  value={mode === "progress" ? progress : scrub}
                  onChange={(e) => {
                    const v = Number(e.target.value);
                    setScrub(v);
                    if (mode === "progress") {
                      setProgress(v);
                    } else {
                      both((h) => {
                        h?.pause();
                        h?.seekFraction(v);
                      });
                      setPlaying(false);
                    }
                  }}
                />
              </div>
            </div>

            <div className="console-section">
              <span className="console-label">Rate</span>
              <div className="seg">
                {rates.map((r) => (
                  <button
                    key={r}
                    type="button"
                    className={rate === r ? "on" : ""}
                    onClick={() => {
                      setRate(r);
                      both((h) => h?.setRate(r));
                    }}
                  >
                    {r}×
                  </button>
                ))}
              </div>
            </div>

            <div className="console-section">
              <span className="console-label">Drive mode</span>
              <div className="seg">
                <button type="button" className={mode === "clock" ? "on" : ""} onClick={() => applyMode("clock")}>
                  Clock
                </button>
                <button
                  type="button"
                  className={mode === "progress" ? "on" : ""}
                  onClick={() => applyMode("progress")}
                >
                  Progress
                </button>
              </div>
              <p className="mode-note">
                {mode === "clock" ? (
                  <>
                    <strong>Clock-driven</strong> — shared ticker plays the doc. Scrub pauses and seeks.
                  </>
                ) : (
                  <>
                    <strong>Progress-driven</strong> — controlled <code>progress</code> prop (0…1). Use for
                    scroll, drag, or external state.
                  </>
                )}
              </p>
            </div>
          </div>
        </aside>
      </div>

      <section className="card cases">
        <div className="card-head">
          <h2>Covered cases</h2>
          <span className="card-meta">shared example flow</span>
        </div>
        <div className="card-body">
          <div className="case-grid">
            {CASES.map((c) => (
              <div key={c.k} className="case">
                <div className="k">
                  <span className="check">✓</span>
                  {c.k}
                </div>
                <div className="v">{c.v}</div>
              </div>
            ))}
          </div>
        </div>
      </section>

      <footer className="lab-foot">
        <span>
          Package <code className="mono">@blinn-motion/react</code>
        </span>
        <span className="sep">·</span>
        <a href="https://docs.blinnmotion.com/adapters/react" target="_blank" rel="noreferrer">
          Adapter docs
        </a>
        <span className="sep">·</span>
        <a href="https://docs.blinnmotion.com/guides/playback" target="_blank" rel="noreferrer">
          Playback guide
        </a>
        <span className="sep">·</span>
        <a href="https://blinnmotion.com" target="_blank" rel="noreferrer">
          blinnmotion.com
        </a>
      </footer>
    </div>
  );
}
