// examples/vue/src/App.vue
<script setup lang="ts">
import { ref, computed, watch } from "vue";
import { BlinnMotion, type BlinnMotionHandle } from "@blinn-motion/vue";
import { fixtures, fixtureList, type FixtureId } from "../../_shared/fixtures";

const docId = ref<FixtureId>("showcase");
const doc = computed(() => fixtures[docId.value]);
const mode = ref<"clock" | "progress">("clock");
const progress = ref(0);
const rate = ref(1);
const playing = ref(true);
const timeLabel = ref("0.00s");
const fracLabel = ref("0%");
const scrub = ref(0);

const domRef = ref<BlinnMotionHandle | null>(null);
const canvasRef = ref<BlinnMotionHandle | null>(null);

const progressProp = computed(() => (mode.value === "progress" ? progress.value : undefined));

function both(fn: (h: BlinnMotionHandle | null) => void) {
  fn(domRef.value);
  fn(canvasRef.value);
}

function onFrame(t: number, f: number) {
  timeLabel.value = `${t.toFixed(2)}s`;
  fracLabel.value = `${Math.round(f * 100)}%`;
  if (mode.value === "clock") scrub.value = f;
}

function toggle() {
  both((h) => h?.toggle());
  playing.value = !playing.value;
}

function restart() {
  both((h) => {
    h?.seek(0);
    if (mode.value === "clock") h?.play();
  });
  playing.value = mode.value === "clock";
}

function onScrub(v: number) {
  scrub.value = v;
  if (mode.value === "progress") {
    progress.value = v;
  } else {
    both((h) => {
      h?.pause();
      h?.seekFraction(v);
    });
    playing.value = false;
  }
}

function setRate(r: number) {
  rate.value = r;
  both((h) => h?.setRate(r));
}

watch(mode, (m) => {
  if (m === "progress") {
    both((h) => h?.pause());
    playing.value = false;
    progress.value = scrub.value;
  } else {
    both((h) => {
      h?.seekFraction(scrub.value);
      h?.play();
    });
    playing.value = true;
  }
});
</script>

<template>
  <div class="demo">
    <div class="stack-badge">Vue 3 · @blinn-motion/vue</div>
    <h1>Blinn Motion · Vue advanced demo</h1>
    <p class="lede">
      Same shared flow as every other stack: MotionDoc switch, dual <code>dom</code> /
      <code>canvas</code> stages, transport controls, scrub, rate, and progress-driven mode via
      <code>&lt;BlinnMotion&gt;</code>.
    </p>

    <div class="stages">
      <div class="panel">
        <p class="panel-label">renderer="dom"</p>
        <div class="stage-host">
          <BlinnMotion
            ref="domRef"
            :doc="doc"
            renderer="dom"
            :loop="true"
            :autoplay="mode === 'clock'"
            :rate="rate"
            :progress="progressProp"
            :on-frame="onFrame"
          />
        </div>
      </div>
      <div class="panel">
        <p class="panel-label">renderer="canvas"</p>
        <div class="stage-host">
          <BlinnMotion
            ref="canvasRef"
            :doc="doc"
            renderer="canvas"
            :loop="true"
            :autoplay="mode === 'clock'"
            :rate="rate"
            :progress="progressProp"
          />
        </div>
      </div>
    </div>

    <div class="panel">
      <p class="panel-label">Transport &amp; cases</p>
      <div class="controls">
        <label class="field">
          MotionDoc
          <select v-model="docId">
            <option v-for="f in fixtureList" :key="f.id" :value="f.id">{{ f.label }}</option>
          </select>
        </label>
        <button class="btn" type="button" @click="toggle">{{ playing ? "❚❚ Pause" : "▶ Play" }}</button>
        <button class="btn ghost" type="button" @click="restart">↺ Restart</button>
        <label class="field">
          Rate
          <select :value="rate" @change="setRate(Number(($event.target as HTMLSelectElement).value))">
            <option :value="0.5">0.5×</option>
            <option :value="1">1×</option>
            <option :value="1.5">1.5×</option>
            <option :value="2">2×</option>
          </select>
        </label>
        <span class="meter">{{ timeLabel }} · {{ fracLabel }}</span>
      </div>

      <div class="mode-row">
        <button class="btn" :class="{ active: mode === 'clock', ghost: mode !== 'clock' }" type="button" @click="mode = 'clock'">
          Clock-driven
        </button>
        <button class="btn" :class="{ active: mode === 'progress', ghost: mode !== 'progress' }" type="button" @click="mode = 'progress'">
          Progress-driven
        </button>
        <div class="progress-block">
          <label class="field" style="flex: 1">
            Scrub / progress
            <input type="range" min="0" max="1" step="0.001" :value="mode === 'progress' ? progress : scrub" @input="onScrub(Number(($event.target as HTMLInputElement).value))" />
          </label>
        </div>
      </div>
      <p class="hint">Progress mode sets the controlled <code>progress</code> prop (0…1) and pauses the ticker — ideal for scroll/gesture.</p>
    </div>

    <div class="cases">
      <div class="case"><strong>Doc switch</strong> card + showcase fixtures</div>
      <div class="case"><strong>Dual stages</strong> DOM vs Canvas same MotionDoc</div>
      <div class="case"><strong>Transport</strong> play / pause / toggle / restart</div>
      <div class="case"><strong>Scrub + rate</strong> seekFraction + setRate</div>
      <div class="case"><strong>Progress mode</strong> controlled 0…1 prop</div>
      <div class="case"><strong>onFrame meter</strong> live time + fraction</div>
    </div>
  </div>
</template>

// examples/svelte/src/App.svelte
<script lang="ts">
  import { blinnMotion, getBlinnHandle, type BlinnMotionHandle } from "@blinn-motion/svelte";
  import { fixtures, fixtureList, type FixtureId } from "../../_shared/fixtures";

  let docId: FixtureId = $state("showcase");
  let mode: "clock" | "progress" = $state("clock");
  let progress = $state(0);
  let rate = $state(1);
  let playing = $state(true);
  let timeLabel = $state("0.00s");
  let fracLabel = $state("0%");
  let scrub = $state(0);

  let domEl: HTMLDivElement | undefined = $state();
  let canvasEl: HTMLDivElement | undefined = $state();

  const doc = $derived(fixtures[docId]);
  const progressOpt = $derived(mode === "progress" ? progress : undefined);

  function both(fn: (h: BlinnMotionHandle | null) => void) {
    fn(getBlinnHandle(domEl));
    fn(getBlinnHandle(canvasEl));
  }

  function onFrame(t: number, f: number) {
    timeLabel = `${t.toFixed(2)}s`;
    fracLabel = `${Math.round(f * 100)}%`;
    if (mode === "clock") scrub = f;
  }

  function toggle() {
    both((h) => h?.toggle());
    playing = !playing;
  }
  function restart() {
    both((h) => {
      h?.seek(0);
      if (mode === "clock") h?.play();
    });
    playing = mode === "clock";
  }
  function onScrub(v: number) {
    scrub = v;
    if (mode === "progress") progress = v;
    else {
      both((h) => {
        h?.pause();
        h?.seekFraction(v);
      });
      playing = false;
    }
  }
  function setRate(r: number) {
    rate = r;
    both((h) => h?.setRate(r));
  }
  function setMode(m: "clock" | "progress") {
    mode = m;
    if (m === "progress") {
      both((h) => h?.pause());
      playing = false;
      progress = scrub;
    } else {
      both((h) => {
        h?.seekFraction(scrub);
        h?.play();
      });
      playing = true;
    }
  }

  const domParams = $derived({
    doc,
    renderer: "dom" as const,
    loop: true,
    autoplay: mode === "clock",
    rate,
    progress: progressOpt,
    onFrame,
  });
  const canvasParams = $derived({
    doc,
    renderer: "canvas" as const,
    loop: true,
    autoplay: mode === "clock",
    rate,
    progress: progressOpt,
  });
</script>

<div class="demo">
  <div class="stack-badge">Svelte 5 · @blinn-motion/svelte</div>
  <h1>Blinn Motion · Svelte advanced demo</h1>
  <p class="lede">
    Idiomatic <code>use:blinnMotion</code> action on host nodes — dual DOM/Canvas stages, full transport,
    scrub, rate, and progress-driven mode.
  </p>

  <div class="stages">
    <div class="panel">
      <p class="panel-label">renderer="dom"</p>
      <div class="stage-host" bind:this={domEl} use:blinnMotion={domParams}></div>
    </div>
    <div class="panel">
      <p class="panel-label">renderer="canvas"</p>
      <div class="stage-host" bind:this={canvasEl} use:blinnMotion={canvasParams}></div>
    </div>
  </div>

  <div class="panel">
    <p class="panel-label">Transport &amp; cases</p>
    <div class="controls">
      <label class="field">
        MotionDoc
        <select bind:value={docId}>
          {#each fixtureList as f}
            <option value={f.id}>{f.label}</option>
          {/each}
        </select>
      </label>
      <button class="btn" type="button" onclick={toggle}>{playing ? "❚❚ Pause" : "▶ Play"}</button>
      <button class="btn ghost" type="button" onclick={restart}>↺ Restart</button>
      <label class="field">
        Rate
        <select value={rate} onchange={(e) => setRate(Number(e.currentTarget.value))}>
          <option value={0.5}>0.5×</option>
          <option value={1}>1×</option>
          <option value={1.5}>1.5×</option>
          <option value={2}>2×</option>
        </select>
      </label>
      <span class="meter">{timeLabel} · {fracLabel}</span>
    </div>
    <div class="mode-row">
      <button class="btn" class:active={mode === "clock"} class:ghost={mode !== "clock"} type="button" onclick={() => setMode("clock")}>Clock-driven</button>
      <button class="btn" class:active={mode === "progress"} class:ghost={mode !== "progress"} type="button" onclick={() => setMode("progress")}>Progress-driven</button>
      <div class="progress-block">
        <label class="field" style="flex:1">
          Scrub / progress
          <input type="range" min="0" max="1" step="0.001" value={mode === "progress" ? progress : scrub} oninput={(e) => onScrub(Number(e.currentTarget.value))} />
        </label>
      </div>
    </div>
    <p class="hint">Progress mode uses controlled <code>progress</code> on the action params (0…1).</p>
  </div>

  <div class="cases">
    <div class="case"><strong>Doc switch</strong> card + showcase fixtures</div>
    <div class="case"><strong>Dual stages</strong> DOM vs Canvas same MotionDoc</div>
    <div class="case"><strong>Transport</strong> play / pause / toggle / restart</div>
    <div class="case"><strong>Scrub + rate</strong> seekFraction + setRate</div>
    <div class="case"><strong>Progress mode</strong> controlled 0…1 param</div>
    <div class="case"><strong>onFrame meter</strong> live time + fraction</div>
  </div>
</div>
